### PR TITLE
Add methods to probe the size of the apk + splits on DownloadData

### PR DESCRIPTION
**Pull request by paulo-raca**
My previous attempt for fiddle with DownloadData was too ambitious....
But it is good enough to be able to get the size of the main APK + splits

### CODE REVIEW

**Comment by onyxbits** [comment]
This one might get you an ArrayOutOfboundsException if n is greater than splitcount()

**Comment by onyxbits** [comment]
Are you sure the returned size should be -1? I would find it more logical to return 0.

**Comment by paulo-raca** [comment]
> Are you sure the returned size should be -1? I would find it more logical to return 0.

I was trying to be consistent with `getMainFileVersion()` / `getPatchFileVersion()`, but you are right, `0` makes more sense.

> This one might get you an ArrayOutOfboundsException if n is greater than splitcount()

This will also happen with `openSplitDelivery()` -- Again, just trying to be consistent

**Comment by onyxbits** [comment]
Aww shit ... Ok ... let's go with consistency then.

**Pull request merged**
