### PR TITLE
Gradle build refactoring and version upgrade (5 to 6) :rocket:

### PR DESCRIPTION
**Pull request by dejan2609**
for rationale see this issue: https://github.com/onyxbits/raccoon4/issues/85

details:
 * version upgrades:
     ** gradle:          5.6.2 -->> 6.7.1
     ** launch4j plugin: 2.4.3 -->> 2.4.9
 * all gradle plugins are moved under 'plugins' section (legacy 'apply' directive is removed)
 * project version is moved to a 'gradle.properties' file (rationale: now IDEs are able to import project without warnings/errors)
 * gradle wrapper section introduced with gradle distribution switched from 'bin' to 'all' (useful for IDEs, among other things)
 * .gitignore file: IntelliJ Idea entry is added
 * deprecated gradle properties are replaced:
     ** 'version'  -->> 'archiveVersion'
     ** 'baseName' -->> 'archiveBaseName'

related links:
 * https://docs.gradle.org/current/userguide/upgrading_version_5.html#changes_for_archive_tasks_zip_jar_war_ear_tar
 * https://docs.gradle.org/6.7.1/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:version
 * https://docs.gradle.org/6.7.1/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:baseName

### CODE REVIEW

**Comment by dejan2609** [comment]
Small change: I'm going to force-push in order to solve GitHub warning **_No new line at the end of file_** 

image

**Comment by dejan2609** [comment]
@onyxbits please review this PR (small note: I will also upgrade your build for Gradle 7.x version at some point).

**Comment by dejan2609** [comment]
@onyxbits can you please review this ?

**Comment by onyxbits** [comment]
Hi, sorry. Been incredibly busy the past few weeks, so I lost sight of this.

**Comment by dejan2609** [comment]
No worries @onyxbits ! Thanks for investing your time to review and merge this.

**Pull request merged**
