### PR TITLE
Improve GooglePlayException: Preserve HTTP status and extract error messages

### PR DESCRIPTION
**Pull request by paulo-raca**
The HTTP status is useful for handling errors in my code -- E.g., I was getting 429 errors, and now I handle it as sleep-and-retry.

The error message used to be the raw response buffer. While it was usable, the protobuf bytes and HTML tags make it noisy.

To handle that, I added a very simple regex to remove HTML tags, and a small function extracts ascii strings from protobuf blobs. If none of the strategies work,
it falls back to the showing the HTTP status line.

While it is a simple (And crappy), I've found them to work well enough:
- HTML error: `<html><body><h1>429 Too Many Requests</h1><p>Please reduce your request rate.</p></body></html>` becomes `429 Too Many Requests - Please reduce your request rate.`
- Protobuf error: `????Item not found.`  becomes  `Item not found.`

### CODE REVIEW

**Comment by onyxbits** [comment]
Parsing a context free grammar (HTML) with a regex? Please, for the love of Chomsky, don't!

**Comment by onyxbits** [comment]
You should never parse protobuf manually. That's a recipe for desaster. If you get a Protocolbuffer there, it should be a ResponseWrapper:

```
ResponseWrapper rw = ResponseWrapper.parseFrom(response.getEntity().getContent());
String reason = response.getStatusLine().getReasonPhrase();
if (rw.hasCommands() && rw.getCommands().hasDisplayErrorMessage()) {
  reason = rw.getCommands().getDisplayErrorMessage();
}
```

**Comment by paulo-raca** [comment]
> Parsing a context free grammar (HTML) with a regex? Please, for the love of Chomsky, don't!

Haha, I'm well aware that this is crappy, but I didn't want to bloat the project with a real HTML parse.

But since the only HTML errors I saw repeats the text from the HTTP status line, I should probably work with that instead

> If you get a Protocolbuffer there, it should be a ResponseWrapper

Thanks! I spend a ridiculous amount of time trying to figure :joy:

**Comment by paulo-raca** [comment]
Thanks for the help, it is so much better now :heart:

**Comment by paulo-raca** [comment]
Thank you !

**Pull request merged**
